// Code generated by "stringer -type=DoubleRule"; DO NOT EDIT

package blackjack

import "fmt"

const _DoubleRule_name = "DoubleAnyDoubleOnly9_10_11DoubleOnly10_11"

var _DoubleRule_index = [...]uint8{0, 9, 26, 41}

func (i DoubleRule) String() string {
	if i < 0 || i >= DoubleRule(len(_DoubleRule_index)-1) {
		return fmt.Sprintf("DoubleRule(%d)", i)
	}
	return _DoubleRule_name[_DoubleRule_index[i]:_DoubleRule_index[i+1]]
}
