// Code generated by "stringer -type=SurrenderRule"; DO NOT EDIT

package blackjack

import "fmt"

const _SurrenderRule_name = "NoSurrenderEarlySurrenderLateSurrender"

var _SurrenderRule_index = [...]uint8{0, 11, 25, 38}

func (i SurrenderRule) String() string {
	if i < 0 || i >= SurrenderRule(len(_SurrenderRule_index)-1) {
		return fmt.Sprintf("SurrenderRule(%d)", i)
	}
	return _SurrenderRule_name[_SurrenderRule_index[i]:_SurrenderRule_index[i+1]]
}
